project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "Metodología I - MCS"
  site-url: "https://metod1-mcs.netlify.app"
  description: "Magister en Ciencias Sociales, mención en Sociología de la Modernización"
  favicon: "/files/icon-513.png"

  twitter-card:
    image: "/files/social-image-f22.png"
    card-style: summary_large_image
    creator: "@juankcastillo"
    site: "@juankcastillo"

  open-graph:
    image: "/files/social-image-f22.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#08C4C4"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Contenidos"
        file: content/index.qmd
#      - text: "Assignments"
#        file: assignment/index.qmd
#      - text: "Examples"
#        file: example/index.qmd
      - trabajos.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - icon: slack
        href: "https://www.slack.com"
        aria-label: Slack

  sidebar:
    - title: "Contenidos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "00: Presentación"
              file: content/01-content.qmd
            - text: "01: Sesión 1"
              file: content/02-content.qmd
            - text: "02: Sesión 2"
              file: content/03-content.qmd
            - text: "03: Sesión 3"
              file: content/04-content.qmd

    - title: "Recursos"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Descripción"
          file: resource/index.qmd
        - text: "Práctica 1"
          file: resource/01-resource.qmd
        - text: "Práctica 2"
          file: resource/02-resource.qmd
        - text: "Práctica 2.2"
          file: resource/02-2-resource.qmd
        - text: "Práctica 3"
          file: resource/03-resource.qmd


  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
